# all-in-one.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: testkubectl

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: testkubectl
type: Opaque
stringData:
  username: admin
  password: admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: testkubectl
data:
  SPRING_PROFILES_ACTIVE: default
  APP_MESSAGE: "Hello from Kubernetes!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkubectl
  namespace: testkubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testkubectl
  template:
    metadata:
      labels:
        app: testkubectl
    spec:
      containers:
        - name: testkubectl
          image: testkubectl:latest   # your image in Minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_MESSAGE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: testkubectl-service
  namespace: testkubectl
spec:
  type: NodePort
  selector:
    app: testkubectl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # optional, else Kubernetes will assign

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testkubectl-ingress
  namespace: testkubectl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: testkubectl.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testkubectl-service
                port:
                  number: 8080
